// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoscrollController from "./autoscroll_controller"
application.register("autoscroll", AutoscrollController)

import ComposeController from "./compose_controller"
application.register("compose", ComposeController)

import DisableInputsController from "./disable_inputs_controller"
application.register("disable-inputs", DisableInputsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
